const { test } = require('node:test');
const assert = require('node:assert/strict');
const m = require('../.model-test/workspace.js');
const row = { id:'a', name:'Dataset', provider:'supabase', kind:'table', source:'Database A', platform:null, detail:'Stored rows', count:0, capturedAt:'2026-09-09T13:10:00Z', url:null };
const snapshot = resources => ({ version:1, capturedAt:'2026-09-09T13:10:00Z', resources });
test('a real zero is preserved', () => assert.equal(m.parseSnapshot(snapshot([row])).resources[0].count,0));
test('separate database counts are not merged', () => assert.equal(m.resourcesWithSnapshot(m.parseSnapshot(snapshot([row,{...row,id:'b',source:'Database B',count:4}]))).filter(r=>r.provider==='supabase').length,2));
test('unassigned tables do not leak into platform filter',()=>assert.equal(m.filterResources([row],'phosphoros','all','all').length,0));
test('search is case insensitive',()=>assert.equal(m.filterResources([row],'all','supabase','Database A','DATA').length,1));
test('source filters are independent',()=>assert.equal(m.filterResources([row],'all','supabase','Database B').length,0));
test('unknown fields never survive import',()=>assert.equal(m.parseSnapshot(snapshot([{...row,apiKey:'DO-NOT-RETAIN'}])).resources[0].apiKey,undefined));
test('duplicate ids rejected',()=>assert.throws(()=>m.parseSnapshot(snapshot([row,row]))));
test('unsafe urls rejected',()=>{for(const url of ['javascript:alert(1)','https://evil.example','https://token@github.com/x','https://github.com.evil.example']) assert.throws(()=>m.parseSnapshot(snapshot([{...row,url}])));});
test('negative, unsafe and fabricated cross-provider counts rejected',()=>{for(const count of [-1,Number.MAX_SAFE_INTEGER+1,NaN]) assert.throws(()=>m.parseSnapshot(snapshot([{...row,count}])));assert.throws(()=>m.parseSnapshot(snapshot([{...row,provider:'vercel',kind:'project',count:12}])));});
test('source-kind mismatch rejected',()=>assert.throws(()=>m.parseSnapshot(snapshot([{...row,provider:'github'}]))));
test('invalid timestamps rejected',()=>assert.throws(()=>m.parseSnapshot({...snapshot([row]),capturedAt:'yesterday'})));
test('valid official source links accepted',()=>assert.equal(m.safeUrl('https://supabase.com/dashboard/project/example'),'https://supabase.com/dashboard/project/example'));
test('count scale includes zero baseline',()=>assert.equal(m.chartMaximum([{...row,count:12},row]),12));
test('move operations are immutable and bounded',()=>{const a=[{id:'1'},{id:'2'}];assert.deepEqual(m.moveBlock(a,'1',1),[{id:'2'},{id:'1'}]);assert.deepEqual(a,[{id:'1'},{id:'2'}]);assert.deepEqual(m.moveBlock(a,'1',-1),a);});
test('local layout validation and caps',()=>{assert.deepEqual(m.parseLayout(m.INITIAL_LAYOUT),m.INITIAL_LAYOUT);assert.deepEqual(m.parseLayout({blocks:[],audiences:[]}).suite,m.INITIAL_LAYOUT.suite);assert.throws(()=>m.parseLayout({blocks:Array(9).fill({}),audiences:[]}));assert.throws(()=>m.parseLayout({blocks:[{id:'1',title:'',kind:'blank',text:''}],audiences:[]}));});
test('sidebar preferences migrate older layouts and round-trip without changing Suite tools', () => {
  const old = { blocks: [], audiences: [], suite: { visible: true, tools: { scratchpad: false, 'data-inspector': true } } };
  const migrated = m.parseLayout(old);
  assert.deepEqual(migrated.sidebar, m.INITIAL_LAYOUT.sidebar);
  const configured = m.parseLayout({ ...migrated, sidebar: { collapsed: true, width: 'wide', search: false, counts: false, secret: 'discard' } });
  assert.deepEqual(configured.sidebar, { collapsed: true, width: 'wide', search: false, counts: false });
  assert.deepEqual(configured.suite, migrated.suite);
  assert.deepEqual(m.parseLayout(JSON.parse(JSON.stringify(configured))), configured);
  assert.deepEqual(m.parseLayout({ ...old, sidebar: { collapsed: 'yes', width: 'invalid' } }).sidebar, m.INITIAL_LAYOUT.sidebar);
});

test('Data tables joins Suite while preserving its master switch and existing tools', () => {
  const previous = { blocks: [], audiences: [], suite: { visible: false, tools: { scratchpad: true, 'data-inspector': true, 'api-sandbox': false, 'command-shelf': true } }, sidebar: { dataTables: false, collapsed: true, search: false, counts: true } };
  const migrated = m.parseLayout(previous);
  assert.equal(migrated.suite.visible, false);
  for (const [name, enabled] of Object.entries(previous.suite.tools)) assert.equal(migrated.suite.tools[name], enabled);
  assert.equal(migrated.suite.tools['data-tables'], false);
  assert.equal(migrated.sidebar.collapsed, true);
  assert.equal(migrated.sidebar.search, false);
  assert.equal('dataTables' in migrated.sidebar, false);
  const explicit = m.parseLayout({ ...previous, suite: { ...previous.suite, visible: true, tools: { ...previous.suite.tools, 'data-tables': true } } });
  assert.equal(explicit.suite.visible, true); assert.equal(explicit.suite.tools['data-tables'], true);
  assert.deepEqual(m.parseLayout(JSON.parse(JSON.stringify(explicit))), explicit);
});
